services:
  - type: web
    name: av-app
    env: python
    plan: starter
    buildCommand: |
      pip install -r requirements.txt && \
      python manage.py collectstatic --noinput && \
      python manage.py migrate
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 3 --error-logfile - --log-level debug
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "localhost,127.0.0.1,0.0.0.0,momo-vusx.onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://momo-vusx.onrender.com"
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_DB_HOST
        sync: false
      - key: SUPABASE_DB_NAME
        sync: false
      - key: SUPABASE_DB_USER
        sync: false
      - key: SUPABASE_DB_PASSWORD
        sync: false
      - key: SUPABASE_DB_PORT
        sync: false
      - key: DATABASE_URL
        sync: false
